// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/svcapi/svcapi.proto

package svcapi

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Svcapi service

func NewSvcapiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Svcapi service

type SvcapiService interface {
	FindSvcById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AddSvc(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteSvcById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateSvc(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 默认接口
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type svcapiService struct {
	c    client.Client
	name string
}

func NewSvcapiService(name string, c client.Client) SvcapiService {
	return &svcapiService{
		c:    c,
		name: name,
	}
}

func (c *svcapiService) FindSvcById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Svcapi.FindSvcById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svcapiService) AddSvc(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Svcapi.AddSvc", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svcapiService) DeleteSvcById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Svcapi.DeleteSvcById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svcapiService) UpdateSvc(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Svcapi.UpdateSvc", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svcapiService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Svcapi.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Svcapi service

type SvcapiHandler interface {
	FindSvcById(context.Context, *Request, *Response) error
	AddSvc(context.Context, *Request, *Response) error
	DeleteSvcById(context.Context, *Request, *Response) error
	UpdateSvc(context.Context, *Request, *Response) error
	// 默认接口
	Call(context.Context, *Request, *Response) error
}

func RegisterSvcapiHandler(s server.Server, hdlr SvcapiHandler, opts ...server.HandlerOption) error {
	type svcapi interface {
		FindSvcById(ctx context.Context, in *Request, out *Response) error
		AddSvc(ctx context.Context, in *Request, out *Response) error
		DeleteSvcById(ctx context.Context, in *Request, out *Response) error
		UpdateSvc(ctx context.Context, in *Request, out *Response) error
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Svcapi struct {
		svcapi
	}
	h := &svcapiHandler{hdlr}
	return s.Handle(s.NewHandler(&Svcapi{h}, opts...))
}

type svcapiHandler struct {
	SvcapiHandler
}

func (h *svcapiHandler) FindSvcById(ctx context.Context, in *Request, out *Response) error {
	return h.SvcapiHandler.FindSvcById(ctx, in, out)
}

func (h *svcapiHandler) AddSvc(ctx context.Context, in *Request, out *Response) error {
	return h.SvcapiHandler.AddSvc(ctx, in, out)
}

func (h *svcapiHandler) DeleteSvcById(ctx context.Context, in *Request, out *Response) error {
	return h.SvcapiHandler.DeleteSvcById(ctx, in, out)
}

func (h *svcapiHandler) UpdateSvc(ctx context.Context, in *Request, out *Response) error {
	return h.SvcapiHandler.UpdateSvc(ctx, in, out)
}

func (h *svcapiHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SvcapiHandler.Call(ctx, in, out)
}
