// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/podapi/podapi.proto

package podapi

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Podapi service

func NewPodapiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Podapi service

type PodapiService interface {
	FindPodById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AddPod(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeletePodById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdatePod(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 默认接口
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type podapiService struct {
	c    client.Client
	name string
}

func NewPodapiService(name string, c client.Client) PodapiService {
	return &podapiService{
		c:    c,
		name: name,
	}
}

func (c *podapiService) FindPodById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Podapi.FindPodById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podapiService) AddPod(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Podapi.AddPod", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podapiService) DeletePodById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Podapi.DeletePodById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podapiService) UpdatePod(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Podapi.UpdatePod", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podapiService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Podapi.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Podapi service

type PodapiHandler interface {
	FindPodById(context.Context, *Request, *Response) error
	AddPod(context.Context, *Request, *Response) error
	DeletePodById(context.Context, *Request, *Response) error
	UpdatePod(context.Context, *Request, *Response) error
	// 默认接口
	Call(context.Context, *Request, *Response) error
}

func RegisterPodapiHandler(s server.Server, hdlr PodapiHandler, opts ...server.HandlerOption) error {
	type podapi interface {
		FindPodById(ctx context.Context, in *Request, out *Response) error
		AddPod(ctx context.Context, in *Request, out *Response) error
		DeletePodById(ctx context.Context, in *Request, out *Response) error
		UpdatePod(ctx context.Context, in *Request, out *Response) error
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Podapi struct {
		podapi
	}
	h := &podapiHandler{hdlr}
	return s.Handle(s.NewHandler(&Podapi{h}, opts...))
}

type podapiHandler struct {
	PodapiHandler
}

func (h *podapiHandler) FindPodById(ctx context.Context, in *Request, out *Response) error {
	return h.PodapiHandler.FindPodById(ctx, in, out)
}

func (h *podapiHandler) AddPod(ctx context.Context, in *Request, out *Response) error {
	return h.PodapiHandler.AddPod(ctx, in, out)
}

func (h *podapiHandler) DeletePodById(ctx context.Context, in *Request, out *Response) error {
	return h.PodapiHandler.DeletePodById(ctx, in, out)
}

func (h *podapiHandler) UpdatePod(ctx context.Context, in *Request, out *Response) error {
	return h.PodapiHandler.UpdatePod(ctx, in, out)
}

func (h *podapiHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.PodapiHandler.Call(ctx, in, out)
}
